apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: web-news
  description: A news aggregator app built with react & currentsapi
spec:
  type: website
  owner: eagles
  lifecycle: production
