apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "Web-News"
  description: A news aggregator app built with React & Currents API
spec:
  type: website
  owner: eagles
  lifecycle: production
