[build]
  command = "yarn build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

[[headers]]
  for = "/dist/*"
  [headers.values]
  "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  # optional, deploy the lighthouse report to a path under your site
  [plugins.inputs.audits]
    output_path = "reports/lighthouse.html"
