export default [
  { icon: "📡", category: "technology" },
  { icon: "💡", category: "business" },
  { icon: "📖", category: "general" },
  { icon: "🩺", category: "science" },
  { icon: "🥁", category: "entertainment" },
  { icon: "⚽️", category: "sports" },
  { icon: "💵", category: "finance" },
  { icon: "👨‍⚖️", category: "politics" },
  { icon: "🏥", category: "health" },
  { icon: "🚘", category: "travel" },
  { icon: "🧫", category: "culture" },
  { icon: "⏳", category: "economy" },
  { icon: "🔒", category: "security" },
];
