export const countries = [
  { key: "US", country: "United State" },
  { key: "TW", country: "Taiwan" },
  { key: "DE", country: "German" },
  { key: "GB", country: "United Kingdom" },
  { key: "CN", country: "China" },
  { key: "IN", country: "India" },
  { key: "ES", country: "Spain" },
  { key: "IT", country: "Italy" },
  { key: "PL", country: "Poland" },
  { key: "AU", country: "Australia" },
  { key: "MY", country: "Malaysia" },
  { key: "SG", country: "Singapore" },
  { key: "CA", country: "Canada" },
  { key: "KR", country: "South Korea" },
  { key: "DK", country: "Denmark" },
  { key: "FR", country: "France" },
  { key: "BE", country: "Belgium" },
  { key: "JP", country: "Japan" },
  { key: "AT", country: "Austria" },
  { key: "PT", country: "Portugal" },
  { key: "PH", country: "Philippines" },
  { key: "HK", country: "Hong Kong" },
  { key: "AR", country: "Argentina" },
  { key: "VE", country: "Venezuela" },
  { key: "BR", country: "Brazil" },
  { key: "FI", country: "Finland" },
  { key: "ID", country: "Indonedia" },
  { key: "VN", country: "Vietnam" },
  { key: "MX", country: "Mexico" },
  { key: "GR", country: "Greece" },
  { key: "NL", country: "Netherlands" },
  { key: "NO", country: "Norway" },
  { key: "NZ", country: "New Zealand" },
  { key: "RU", country: "Russia" },
  { key: "SA", country: "Saudi-Arabia" },
  { key: "CH", country: "Switzerland" },
  { key: "TH", country: "Thailand" },
  { key: "AE", country: "United Arab Emirates" },
  { key: "IE", country: "Ireland" },
  { key: "IR", country: "Iran" },
  { key: "IQ", country: "Iraq" },
  { key: "RO", country: "Romania" },
  { key: "AF", country: "Afghanistan" },
  { key: "ZW", country: "Zimbabwe" },
  { key: "MM", country: "Myanmar" },
  { key: "SE", country: "Sweden" },
  { key: "PE", country: "Peru" },
  { key: "PA", country: "Panama" },
  { key: "EG", country: "Egypt" },
  { key: "TR", country: "Turkey" },
  { key: "IL", country: "Israel" },
  { key: "CZ", country: "Czech Republic" },
  { key: "BD", country: "Bangladesh" },
  { key: "NG", country: "Nigeria" },
  { key: "KE", country: "Kenya" },
  { key: "CL", country: "Chile" },
  { key: "UY", country: "Uruguay" },
  { key: "EC", country: "Ecuador" },
  { key: "RS", country: "Serbia" },
  { key: "HU", country: "Hungary" },
  { key: "SI", country: "Slovenia" },
  { key: "GH", country: "Ghana" },
  { key: "BO", country: "Bolivia" },
  { key: "PK", country: "Pakistan" },
  { key: "CO", country: "Colombia" },
  { key: "NK", country: "North Korea" },
  { key: "PY", country: "Paraguay" },
  { key: "PS", country: "Palestine" },
  { key: "EE", country: "Estonia" },
  { key: "LB", country: "Lebanon" },
  { key: "QA", country: "Qatar" },
  { key: "KW", country: "Kuwait" },
  { key: "KH", country: "Cambodia" },
  { key: "NP", country: "Nepal" },
  { key: "LU", country: "Luxembourg" },
  { key: "BA", country: "Bosnia" },
];
